blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ í† ë¡ 
    url: https://github.com/techeer-11-team-k/test/discussions
    about: í”„ë¡œì íŠ¸ì— ëŒ€í•œ ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì„ ì‹œì‘í•˜ì„¸ìš”

